@TechChallenge.API.Register_HostAddress = https://localhost:7001

POST {{TechChallenge.API.Register_HostAddress}}/api/contacts/Register
Content-Type: application/json
{ "Name" : "Tiago", "Phone": "978345689", "Email": "tiago@gmail.com", "DDD": 11 }

###
