resources:
  - k8s/deploy-sqlserver.yaml
  - k8s/deploy-rabbitmq.yaml
  - k8s/api-add.yaml
  - k8s/api-delete.yaml
  - k8s/api-get.yaml
  - k8s/api-update.yaml
  - k8s/tech-consumer.yaml
  - k8s/deploy-prometheus.yaml
  - k8s/deploy-grafana.yaml
